// Code generated by go generate ./pkg/browserprotocol; DO NOT EDIT.

export const BROWSER_VIEWPORT_WIDTH = 1280;
export const BROWSER_VIEWPORT_HEIGHT = 720;
export const BROWSER_STATE_RETENTION_MS = 2592000000;
